# Generated by Django 5.0.4 on 2024-05-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Estrela', 'ESTRELA'), ('Nebulosa', 'NEBULOSA'), ('Constelação', 'CONSTELAÇÃO'), ('Galáxia', 'GALÁXIA'), ('Planeta', 'PLANETA')], default='', max_length=150),
        ),
    ]
